apiVersion: v1
kind: Service
metadata:
  name: web-application-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: web-application
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30101