apiVersion: v1
kind: Service

metadata:
  name: postgres-service
  labels:
    app: postgres
spec:
  selector:
    service: postgres-service
  type: ClusterIP
  ports:
    - name: postgres-port
      protocol: TCP
      port: 5432
      targetPort: 5432