version: "1"

services:
  web:
    image: nosarevandrey/flask-web-application:latest
    environment:
      - USERNAME=admin
      - PASSWORD=admin
      - HOST=db
      - DBNAME=ChatAppDB
    stop_signal: SIGINT
    ports:
      - "3000:8080"
  db:
    build:
      context: ./db
      dockerfile: Dockerfile-pg
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    build:
      context: ./pgAdmin
      dockerfile: Dockerfile-pgAdmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
